language: node_js
node_js:
- '10.10.0'
dist: trusty
sudo: true
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9876 http://localhost &
install:
  - npm install
  # - npm install -g karma-cli
  # - npm install -g bower
env:
  global:
    - B_NAME1=develop
    - B_NAME2=master
    - B_NAME3=test
    #- GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta
    #- if [ "$TRAVIS_BRANCH"=master]; then B_NAME=master; elif [ "$TRAVIS_BRANCH"=develop] then B_NAME=develop; else B_NAME=test; fi
    #- if [ "$TRAVIS_BRANCH"=develop]; then B_NAME=develop; fi
    #- if [ "$TRAVIS_BRANCH"=test]; then B_NAME=test; fi
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - export CHROME_BIN=chromium-browser
    # Print build info that binary is compiled with.
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $B_NAME
script:
  - npm run build
  - npm run test-headless
  - npm run server:test:unit
  # - npm run lint

 # - xvfb-run npm run e2e
before_deploy:
    - if [ "$TRAVIS_BRANCH"=master ]; then B_NAME=master; fi
    #- if [ "$TRAVIS_BRANCH"=develop ]; then B_NAME=develop; fi
    #- if [ "$TRAVIS_BRANCH"=test ]; then B_NAME=test; fi
    #- echo $B_NAME
    - if [ "$TRAVIS_BRANCH" = master ]; then echo "master"; mv index_uat.html index.html; fi
    - if [ "$TRAVIS_BRANCH" = test ]; then echo "test"; mv index_staging.html index.html; fi
deploy:
  - provider: cloudfoundry
    api: https://api.cloud.service.gov.uk
    username: nmdsdevopsserviceadm@hotmail.com
    password:
      secure: "uEQC9KJwyjzJhH9wYb6XTdFY0WoZF0vFJrEHb8ZiL4HaBTLITGDhl9VujxHQHMMmDQzwhJlW+1V5Y4G7J9uw0rJ+XW+FsIzVpZi+SXd0CUmYYwOrMMTsqNivWuOC8rZ1TXAkhvy6jkwFkDrrQcZeO36IitEqRFcEBX5YKQP2gZ2mqw6RzO3X++8uNHIoYu8/ftszAQkQlcFQBbBNbQtj6sNx30jyUi8SwMJakPtWGyce36VhjK2brK8gLUKbGjbL4j6epsTesMCCo5WgVHeMzppp0yqDo5gpBKcelIRhU/Ja8/rLbpIqUVy+ov5ITCVgrefrckYOBoL5FvB7x6i6MfRZZudYGl6oM/g8zLH+IItHsyawPDa1/UnEE5FZAQ/BHq7pqnnF7qbXlO5loRAstpiRssMettNe7ISYnecew3/OAALvomPQlbc942tdiDtIyDzqCyKe2CzWEbL7TSiNBPdA7W5tTWRusnxD/hhwwbrR61FuTKv8V9l5ioCwWBu0OVSbAXErDsWrSI++4FHylnoVk1U2ULS773JiU/uvdu4qWPfWaLkIv0nERGWkCcE7U/M6VBzKiimkbEloMYvvc2LVVSByfaMxeMopHrfrCaeunNlzyB0jzHuOkcIY1SU4y2oE97ES5FgYnzz1akXph0HJw9EjWtNO9SAqtb44XzM="
    organization: dhsc-skills-for-care-nmds-sc-2
    space: sandbox
    manifest: manifest.test.yml
    on:
        branch: test
  - provider: cloudfoundry
    api: https://api.cloud.service.gov.uk
    username: nmdsdevopsserviceadm@hotmail.com
    password:
      secure: "uEQC9KJwyjzJhH9wYb6XTdFY0WoZF0vFJrEHb8ZiL4HaBTLITGDhl9VujxHQHMMmDQzwhJlW+1V5Y4G7J9uw0rJ+XW+FsIzVpZi+SXd0CUmYYwOrMMTsqNivWuOC8rZ1TXAkhvy6jkwFkDrrQcZeO36IitEqRFcEBX5YKQP2gZ2mqw6RzO3X++8uNHIoYu8/ftszAQkQlcFQBbBNbQtj6sNx30jyUi8SwMJakPtWGyce36VhjK2brK8gLUKbGjbL4j6epsTesMCCo5WgVHeMzppp0yqDo5gpBKcelIRhU/Ja8/rLbpIqUVy+ov5ITCVgrefrckYOBoL5FvB7x6i6MfRZZudYGl6oM/g8zLH+IItHsyawPDa1/UnEE5FZAQ/BHq7pqnnF7qbXlO5loRAstpiRssMettNe7ISYnecew3/OAALvomPQlbc942tdiDtIyDzqCyKe2CzWEbL7TSiNBPdA7W5tTWRusnxD/hhwwbrR61FuTKv8V9l5ioCwWBu0OVSbAXErDsWrSI++4FHylnoVk1U2ULS773JiU/uvdu4qWPfWaLkIv0nERGWkCcE7U/M6VBzKiimkbEloMYvvc2LVVSByfaMxeMopHrfrCaeunNlzyB0jzHuOkcIY1SU4y2oE97ES5FgYnzz1akXph0HJw9EjWtNO9SAqtb44XzM="
    organization: dhsc-skills-for-care-nmds-sc-2
    space: sandbox
    manifest: manifest.featureGDS.yml
    on:
        branch: develop_accessibility_demo
notifications:
    slack: skills-for-care:Co9S4WS4ZitevGOyBrEb6yEL


