language: node_js
node_js:
- '10.8'
deploy:
  provider: cloudfoundry
  username: nmdsdevopsserviceadm@hotmail.com
  password:
    secure: bLR4VNV7hMX0JrE93LqYLmecbyxFURttDKliCbZtrkURIUV0XHb47n38Ybi+XzS8bZNqOznaEow79lqJM6plCIuY0DVEACbvol0WE31Fd2glAJ7r/Z4oSIyvs+f6Nnym1MXbyfFmh6vTRmfUAUctjIlGPs3Nc0eFa2sA/zJsZYD1jneSnCjcX6Sj6kVM8zrvk3Oi2SRiILgcg6PH1PuocVHtH0+nTlpR0d07I4Fn5N8DJ9zy7v6wLyKDkTAAlrijFqQm9f2qOcdr3He1+JTETE+4f0nXnUDQ8OHBm28G0vnth8JMZf/h7xwoc6EuRnCbYWa2UJKFLJUhyNb3DvaAe3z5VKYlTN4v4Q4uo/MfIR5rnugyBo3I/XGQzU00PUm1OzuH/zVQdxUKb/mxHdTun1cE70ZPbRBwN750jS4BYyPLvR4/AluYfWbKZ/dfniYHlFxiuXjOYjr9fstsx1KOzcsDXjPBfms/b5VomFlQ60ld9XVhSLxZ4XUQNI8ZoB9uNiuEWcIuCILgZcbWd1pFbW/o/A6LarLsEK/KBtftvfvo8mQUNIpth/31OioYCVELj623zhimVz7CXVyO+VuVbEE/FnoKcZJAR43P2JFQGFA6f51eTvPjMf9q8xYKsQbFmckTyHwrhtdI+LQRlfBEzRhVvLR9bDYAErfYFWVwz1E=
  api: https://api.cloud.service.gov.uk
  organization: dhsc-skills-for-care-nmds-sc-2
  space: sandbox
