aws:
    region: eu-west-1
    secrets:
        use: false
        wallet: dev/api
slack:
    level: 0    # disables Slack notifications
jwt:
    iss: 'localhost'
    ttl:
        login: 60
db:
    pool: 5
    ssl: true
    username: sfcapp
    client_ssl:
        status: true
        usingFiles: false
log:
    sequelize: false

bulkupload:
    region: eu-west-2
    bucketname: sfc-bulkupload-dev