aws:
    region: eu-west-1
    secrets:
        use: true
        wallet: staging/api

db:
    ssl: true
    username: sfcapp
    database: sfctstdb
    client_ssl:
        status: true
        usingFiles: false
